<?php

namespace AppBundle\Repository;

/**
 * NoteFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteFilesRepository extends \Doctrine\ORM\EntityRepository
{
}
