<?php

namespace AppBundle\Repository;

/**
 * RoomNotesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomNotesRepository extends \Doctrine\ORM\EntityRepository
{
}
