<?php

namespace AppBundle\Repository;

/**
 * RoomMemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomMemberRepository extends \Doctrine\ORM\EntityRepository
{
}
