<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPublicRoomsByName($name, User $user)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.name LIKE :value')
            ->orWhere('a.url LIKE :value')
            ->andWhere('a.public = true OR a.user = :user')
            ->setParameter('value', '%'.$name.'%')
            ->setParameter('user', $user)
            ->orderBy('a.edited', 'DESC');

        return $query->getQuery()->getResult();
    }
}
